import json
from typing import Dict, Any, List, Optional, AsyncGenerator
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
import os

class WorkerAgent:
    def __init__(self, json_path: str = "PageIndex/results/document_structure.json"):
        # We will use a fast model for tree traversal to save time/cost
        self.routing_llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
        # We use a potentially stronger/similar model for final answer generation
        self.answering_llm = ChatOpenAI(model="gpt-4o", temperature=0)
        
        self.json_path = json_path
        
        self.node_selection_prompt = PromptTemplate.from_template(
            "You are an expert document retrieval agent.\n"
            "Your task is to review a list of document sections (provided with their titles and summaries) "
            "and determine which sections are most likely to contain the answer to the user's query.\n\n"
            "Chat History / Context: {history}\n\n"
            "User Query: '{query}'\n\n"
            "Available Sections:\n"
            "{sections}\n\n"
            "Return the 'node_id's of up to 3 most relevant sections, ranked from most to least relevant, separated by commas.\n"
            "If none seem relevant at all, return 'NONE'.\n"
            "Do not provide any other text."
        )
        
        self.answer_generation_prompt = PromptTemplate.from_template(
            "You are a helpful expert assistant. Using ONLY the provided context from a document, "
            "answer the user's question. Cite the section title in your answer.\n\n"
            "Chat History: {history}\n\n"
            "Section Title: {title}\n"
            "Context Text:\n{text}\n\n"
            "User Query: {query}\n\n"
            "If the context does not contain the answer, return EXACTLY the phrase 'I cannot find the answer in the document.' and nothing else."
        )

    def _load_document_tree(self) -> List[Dict[Any, Any]]:
        """Loads the JSON tree generated by PageIndex."""
        if not os.path.exists(self.json_path):
            return []
            
        with open(self.json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            
        if isinstance(data, dict) and "structure" in data:
            return data["structure"]
        elif isinstance(data, list):
            return data
        else:
            return []

    async def _evaluate_nodes(self, query: str, history: str, nodes: List[Dict]) -> List[str]:
        """Uses LLM to pick the top 3 relevant nodes from a list of siblings based on summaries."""
        if not nodes:
            return []
            
        sections_text = ""
        for i, node in enumerate(nodes):
            node_id = node.get("node_id", f"missing_id_{i}")
            title = node.get("title", "Untitled")
            summary = node.get("summary", "No summary available.")
            sections_text += f"- node_id: {node_id}\n  Title: {title}\n  Summary: {summary}\n\n"
            
        chain = self.node_selection_prompt | self.routing_llm
        response = await chain.ainvoke({"query": query, "history": history, "sections": sections_text})
        selected_text = response.content.strip().strip("'").strip('"')
        
        if selected_text.upper() == "NONE" or not selected_text:
            return []
            
        # Parse comma-separated list
        selected_ids = [s.strip() for s in selected_text.split(',') if s.strip()]
        return selected_ids[:3]

    async def _recursive_search(self, query: str, history: str, current_nodes: List[Dict], yield_func) -> List[Dict]:
        if not current_nodes:
            return []

        await yield_func(f"Evaluating {len(current_nodes)} sections at current level...")
        best_node_ids = await self._evaluate_nodes(query, history, current_nodes)
        
        if not best_node_ids:
            return []

        candidates = []
        for node_id in best_node_ids:
            selected_node = next((n for n in current_nodes if str(n.get("node_id")) == node_id), None)
            if not selected_node:
                continue
                
            children = selected_node.get("nodes", [])
            if children and len(children) > 0:
                await yield_func(f"Drilling down into section: {selected_node.get('title', 'Unknown')}")
                deep_results = await self._recursive_search(query, history, children, yield_func)
                if deep_results:
                    candidates.extend(deep_results)
                else:
                    candidates.append(selected_node)
            else:
                candidates.append(selected_node)
                
        return candidates

    async def search_and_answer_stream(self, query: str, history_msgs: List[Dict] = []) -> AsyncGenerator[str, None]:
        """Main entry point for document retrieval and answering using Async Generator."""
        # Convert history to a readable string for prompts
        history_str = "\n".join([f"{msg['role'].capitalize()}: {msg['content']}" for msg in history_msgs])
        if not history_str:
            history_str = "No prior history."

        document_tree = self._load_document_tree()
        if not document_tree:
            yield json.dumps({"type": "answer", "content": "The document tree is empty or has not been generated yet. Please upload a PDF."})
            return

        async def yield_status(status_msg: str):
            yield json.dumps({"type": "status", "content": status_msg})

        # We must use a separate async function to collect from the recursion without mixing yields
        # because recursive async generators are complex. We'll pass a callback.
        candidates = []
        
        # Define a wrapper for yielding status back to the main generator
        yield_queue = []
        async def queue_status(msg):
            yield_queue.append(msg)
            
        yield json.dumps({"type": "status", "content": "Starting document search..."})
        
        # Traverse the tree asynchronously
        candidates = await self._recursive_search(query, history_str, document_tree, queue_status)
        
        # Yield any statuses collected during recursion
        for msg in yield_queue:
            yield json.dumps({"type": "status", "content": msg})
            
        if not candidates:
            yield json.dumps({"type": "answer", "content": "I could not find a relevant section in the document to answer your query."})
            return
            
        yield json.dumps({"type": "status", "content": f"Found {len(candidates)} candidate sections. Analyzing text..."})
        
        for i, node in enumerate(candidates):
            title = node.get("title", "Unknown Section")
            text = node.get("text", "")
            
            if not text.strip():
                text = node.get("summary", "No detailed text available.")
                
            yield json.dumps({"type": "status", "content": f"Reading Section: {title}..."})
            
            chain = self.answer_generation_prompt | self.answering_llm
            final_response = await chain.ainvoke({
                "title": title,
                "text": text,
                "query": query,
                "history": history_str
            })
            
            answer = final_response.content.strip()
            
            if answer == "I cannot find the answer in the document.":
                yield json.dumps({"type": "status", "content": f"Section '{title}' did not contain the answer. Checking next..."})
                continue
            else:
                yield json.dumps({"type": "status", "content": "Answer found!"})
                yield json.dumps({"type": "answer", "content": answer})
                return
                
        yield json.dumps({"type": "answer", "content": "I could not find the answer in the document."})
